### ISSUE TITLE
add 'rot' and 'over' words

### ISSUE THREAD

**Issue by mrob27** [polm/dupdupdraw#4]
I have a working interactive sandbox at mrob.com/users/mccann

I have added the standard FORTH words rot and over:

```
// This goes near beginning of "function Parser(x, y, t){"
  this$.over = bind$(this$, 'over', prototype);
  this$.rot = bind$(this$, 'rot', prototype);

// This goes after definition of prototype.dup
prototype.over = function(){
  // over   ( a b -- a b a )
  var a, b;
  b = this.pop();
  a = this.pop();
  this.push(a);
  this.push(b);
  return this.push(a);
};
prototype.rot = function(){
  // rot   ( a b c -- b c a )
  var a, b, c;
  c = this.pop();
  b = this.pop();
  a = this.pop();
  // if (this.x==0) { console.info("rot: "+c+","+b+","+a); };
  this.push(b);
  this.push(c);
  return this.push(a);
};
```

These would be nice to have in the official version

**Comment by polm** [comment]
Thanks for the bug report - these were in the Livescript source (and thus already work in the Twitter version) but were not included in the compiled Javascript previously. I just did a lot of cleanup to make building more straightforward and included the latest JS build, so this should be ok now.

**Comment by mrob27** [comment]
Thank you!

I know it's a bit jolting when somebody comes out of the blue to an old
project and starts doing a lot of unexpected stuff. You handled it with
grace and enthusiasm!

I kind of started to realise I had an outdated version.  My
forthcanvas-browser.js had come from Bradley Momberger, back on 2015 Mar
27th.

By the time I got around to noticing rot was "missing" I had forgotten all
about the Livescript.

I added another issue which you should feel free to ignore if it doesn't
make sense. I'm suggesting maybe dupdupdraw.ls could be separated into a
"big" piece that has all the code that ends up being identical in the two
JS output files, plus one or two "small" pieces with the
environment-specific glue. I don't know if that makes sense or is even
possible... but there "ought" to be a way to make a file containing
JavaScript, which can be used within a Node.js program _or_ as a <"script
src="..."> within HTML for the browser environment.

On Sat, Jan 30, 2016 at 1:33 AM, polm notifications@github.com wrote:

> Thanks for the bug report - these were in the Livescript source (and thus
> already work in the Twitter version) but were not included in the compiled
> Javascript previously. I just did a lot of cleanup to make building more
> straightforward and included the latest JS build, so this should be ok now.

## 

  Robert Munafo  --  mrob.com
  Follow me at: gplus.to/mrob - fb.com/mrob27 - twitter.com/mrob_27 -
mrob27.wordpress.com - youtube.com/user/mrob143 - rilybot.blogspot.com

**Comment by mrob27** [comment]
Closing this issue now: rot and over were always there, I had just been working with an outdated "forthcanvas.js"
