### ISSUE TITLE
Possible way to do both Node.js and Browser

### ISSUE THREAD

**Issue by mrob27** [polm/dupdupdraw#5]
As it stands presently, **pages/dupdupdraw.browser.js** shares a lot of code with the Node.js version (**lib/dupdupdraw.js**); but both of these come from the same original LiveScript source (in **dupdupdraw.ls**).

Perhaps there is a way to break the LiveScript source into a "big" piece that contains all that code that ends up being exactly the same in both versions, and one or two "small" pieces with the environment-specific "glue".

I don't have any Node.js experience so I don't know how that would be done, and I'm not even able to install the tools to try things out, so i don't know if this is a useful idea. Please ignore if not!

**Comment by polm** [comment]
Sorry, I don't understand what you're suggesting. What problem are you trying to solve?

**Comment by mrob27** [comment]
I am unable to install Node.js _or_ browserify _or_ Livescript. Therefore, I do all of my work by editing the Javascript in dupdupdraw.browser.js. That is wrong because I am editing a file that gets generated by something in the Makefile.

As it is structured right now, even if I could install Livescript, I would still be unable to do development in the intended way, because the browserify step would fail. But if you break the source file up into pieces, then you can break the build into pieces. Make a build target that just builds the node-js-free standalone code without "require" statements. Add another build target that builds the glue needed to make it run under node.js. I suppose there's glue for the browser version too, to get the Canvas object to work?

So there would be three build targets: "common", "nodejs-glue", and "browser-glue"

"make all" would build all three, "make ddd-node" would build the common + nodejs-glue, and "make ddd-browser" would make the common + browser-glue.

**Comment by polm** [comment]
OK, thank you for clarifying your issue, I understand what you were trying to say now. 

Unfortunately the only straightforward way to put different pieces of Javascript together in node is by using `require`. Simply appending files might work now but cause terrible things to happen later due to things like variable hoisting causing code to not be interpreted in order. I could remove the server parts to get rid of `require`, but since the server is the primary use case for me that wouldn't really make sense. 

If you want to have a go at a browser-only version or something along the lines of what you suggested please feel free to fork the project (it's public domain).

**Comment by mrob27** [comment]
Oh, I think I understand, and that makes sense.

I'd rather not fork, as it's nice to have the unified cross-platform solution all in one place, and to be realistic, almost everybody can install Node.js + browserify + Livescript + anything else.

The things I've thought of doing are very limited, and easy to reimplement in Livescript (and probably could be re-implemented in a better way). For example I might add an "issue" showing how I added HSV colours as a option, but probably you'll have an idea for how to do it better. I put the word "hsv" at the beginning of the the Forth program to tell it I want everything drawn in HSV, which suggests that the word "rgb" (which presently just pops three things off the stack and ignores them) would want to be renamed and/or redefined.

**Comment by polm** [comment]
Thanks for your understanding; I'm going to go ahead and close this but please feel free to open an issue for any feature you implement or would like to see.

About HSV, it sounds great and I've been thinking of adding modal words like that, but I have no idea how HSV works so an example would be helpful there. Anyway, that's for another time and another issue.
